apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: annuaire-preview
  namespace: argocd
spec:
  generators:
    - pullRequest:
        github:
          owner: rayanSalhi
          repo: tp-argocd
          tokenRef:
            secretName: github-token
            key: token
        requeueAfterSeconds: 30
  template:
    metadata:
      name: "annuaire-preview-{{number}}"
    spec:
      project: devhub
      source:
        repoURL: https://github.com/rayanSalhi/tp-argocd.git
        targetRevision: "{{head_sha}}"
        path: devhub-campus/services/annuaire/chart
        helm:
          valueFiles:
            - values.yaml
            - values-preview.yaml
          parameters:
            - name: ingress.host
              value: "annuaire-preview-{{number}}.devhub.local"
      destination:
        server: https://kubernetes.default.svc
        namespace: "devhub-preview-{{number}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
