replicaCount: 1
image:
  repository: nginx
  tag: "version-qui-nexiste-pas"
  pullPolicy: IfNotPresent
service:
  port: 80
env:
  LOGLEVEL: info
ingress:
  enabled: true
  host: annuaire.devhub.local
resources: {}
