apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devhub
  namespace: argocd
spec:
  description: Plateforme DevHub Campus
  sourceRepos:
    - https://github.com/rayanSalhi/tp-argocd.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: devhub-dev
    - server: https://kubernetes.default.svc
      namespace: devhub-preview-*
    - server: https://kubernetes.default.svc
      namespace: argocd
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: argoproj.io
      kind: Application
    - group: argoproj.io
      kind: AppProject
    - group: argoproj.io
      kind: ApplicationSet
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
